FROM python:3.12-slim

WORKDIR /app

# 复制依赖文件并安装
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple

# 复制整个项目（测试脚本、配置、工具等）
COPY . .

# 默认命令：运行宠物测试（可覆盖）
CMD ["pytest", "testcases/test_pet.py", "--alluredir=/app/reports/allure_raw"]

RUN apt-get update && apt-get install -y netcat-openbsd && rm -rf /var/lib/apt/lists/*